###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

miaoxing-memcached:
  image: phpdockerio/memcached:latest
  container_name: miaoxing-memcached

miaoxing-redis:
  image: phpdockerio/redis:latest
  container_name: miaoxing-redis

miaoxing-mysql:
  image: mysql:5.6
  container_name: miaoxing-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=mypassword
    - MYSQL_DATABASE=app
    - MYSQL_USER=root
    - MYSQL_PASSWORD=mypassword

miaoxing-webserver:
  image: phpdockerio/nginx:latest
  container_name: miaoxing-webserver
  volumes:
      - ..:/var/www/miaoxing
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - miaoxing-php-fpm

miaoxing-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: miaoxing-php-fpm
  volumes:
    - ..:/var/www/miaoxing
    - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - miaoxing-memcached
    - miaoxing-mysql
    - miaoxing-redis
