FROM miaoxing/php56-fpm:latest

# Install rocketeer to deploy project
RUN curl -O http://rocketeer.autopergamene.eu/versions/rocketeer.phar \
    && chmod +x rocketeer.phar \
    && mv rocketeer.phar /usr/local/bin/rocketeer