#!/bin/sh

cp -r ../laradock/php-fpm/* .

docker build \
    --build-arg LARADOCK_PHP_VERSION=7.3 \
    --build-arg INSTALL_EXIF=true \
    --build-arg INSTALL_GMP=true \
    --build-arg INSTALL_IMAGEMAGICK=true \
    --build-arg INSTALL_OPCACHE=true \
    --build-arg INSTALL_PCNTL=true \
    --build-arg INSTALL_PHPREDIS=true \
    --build-arg INSTALL_SOAP=true \
    -t $IMAGE_NAME .
