name: Build and push docker images

on:
  push:
    branches: [ main ]
    tags: [ '**' ]
  workflow_dispatch:

env:
  TAG: $([ ${GITHUB_REF#refs/*/} == "main" ] && echo "latest" || echo ${GITHUB_REF#refs/*/})

jobs:
  php-fpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ 7.3, 7.4, 8.2 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-cache-${{ github.job }}-{hash}
          restore-keys: docker-cache-${{ github.job }}-
      - name: Build the Docker image
        run: |
          export IMAGE_NAME=miaoxing/php-fpm-base:${{ env.TAG }}-${{ matrix.php_version }}
          cd php-fpm-base-${{ matrix.php_version }}
          ./hooks/build

          cd ../php-fpm-${{ matrix.php_version }}
          docker build . -t miaoxing/php-fpm:${{ env.TAG }}-${{ matrix.php_version }}

          docker image ls
      - name: Push image to Docker hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push miaoxing/php-fpm-base:${{ env.TAG }}-${{ matrix.php_version }}
          docker push miaoxing/php-fpm:${{ env.TAG }}-${{ matrix.php_version }}
          docker logout

  php-worker:
    needs: php-fpm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ 7.3, 7.4, 8.2 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-cache-${{ github.job }}-{hash}
          restore-keys: docker-cache-${{ github.job }}-
      - name: Build the Docker image
        run: |
          cd php-worker-${{ matrix.php_version }}
          docker build . -t miaoxing/php-worker:${{ env.TAG }}-${{ matrix.php_version }}
          docker image ls
      - name: Push image to Docker hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push miaoxing/php-worker:${{ env.TAG }}-${{ matrix.php_version }}
          docker logout

  nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-cache-${{ github.job }}-{hash}
          restore-keys: docker-cache-${{ github.job }}-
      - name: Build the Docker image
        run: |
          cd nginx
          docker build . -t miaoxing/nginx:${{ env.TAG }}
          docker image ls
      - name: Push image to Docker hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push miaoxing/nginx:${{ env.TAG }}
          docker logout
